# Generated by Django 5.0.6 on 2024-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_client_country_client_emirates_invoice_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
