# Generated by Django 5.0.6 on 2024-07-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_course_alter_invoice_date_invoice_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='person',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
