# Generated by Django 5.0.6 on 2024-07-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_payed',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
