# Generated by Django 5.0.6 on 2024-07-05 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoicepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='dates',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
