# Generated by Django 5.0.6 on 2024-07-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='person',
            new_name='number_of_person',
        ),
        migrations.RenameField(
            model_name='invoicepurchase',
            old_name='person',
            new_name='number_of_person',
        ),
    ]
