# Generated by Django 5.0.6 on 2024-07-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_rename_person_invoice_number_of_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_payed',
            new_name='amount_paid',
        ),
    ]
