# Generated by Django 5.0.6 on 2024-07-10 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_rename_amount_payed_invoice_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.course'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.course'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
