# Generated by Django 5.0.6 on 2024-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_invoice_dates_remove_invoiceitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepurchase',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
