# Generated by Django 5.0.6 on 2024-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoicepurchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='payment',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
