# Generated by Django 5.0.6 on 2024-07-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoice_payment_invoicepurchase_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Account Transfer', 'Account Transfer'), ('Payment Link', 'Payment Link'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='payment',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash'), ('Account Transfer', 'Account Transfer'), ('Payment Link', 'Payment Link'), ('Cheque', 'Cheque')], max_length=20),
        ),
    ]
