# Generated by Django 5.0.6 on 2024-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_quotation_quotationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='training_venue',
            field=models.CharField(choices=[('orbit', 'Orbit Training (In-House)'), ('company', 'Company Premises (External)'), ('online', 'Online')], max_length=50),
        ),
    ]
