# Generated by Django 5.0.6 on 2024-07-26 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_quotation_training_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('registration_type', models.CharField(choices=[('OT', 'Individual'), ('OC', 'Corporate')], default='OT', max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=100)),
                ('uid_no', models.CharField(blank=True, max_length=100)),
                ('emirates_id_no', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('alternative_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('company_or_university_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='training_venue',
            field=models.CharField(choices=[('Orbit Training (In-House)', 'Orbit Training (In-House)'), ('Company Premises (External)', 'Company Premises (External)'), ('online', 'Online')], max_length=50),
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_contents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='invoices.course')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_location', models.CharField(max_length=255)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_details', to='invoices.registration')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.registration'),
        ),
        migrations.CreateModel(
            name='RegistrationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_courses', to='invoices.registration')),
            ],
            options={
                'unique_together': {('registration', 'course')},
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='courses',
            field=models.ManyToManyField(through='invoices.RegistrationCourse', to='invoices.course'),
        ),
    ]
