# Generated by Django 5.0.6 on 2024-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_registration_alter_quotation_training_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='consultant_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
