# Generated by Django 5.0.6 on 2024-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_registration_consultant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
    ]
