# Generated by Django 5.0.6 on 2024-08-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_certificate_course_code_certificateupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
