# Generated by Django 5.0.6 on 2024-08-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('khda', 'KHDA')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='uploaded_certificate',
            field=models.FileField(blank=True, null=True, upload_to='khda_certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
