# Generated by Django 5.0.6 on 2024-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_certificate_certificate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='emirates',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
