# Generated by Django 5.0.6 on 2024-09-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_course_batch_rate_course_online_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
    ]
