# Generated by Django 5.0.6 on 2024-09-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_companyprofile_user_trainerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='user',
        ),
    ]
