# Generated by Django 5.0.6 on 2024-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_companyprofile_user_trainerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
