# Generated by Django 5.0.6 on 2024-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_alter_quotationitem_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
