# Generated by Django 5.0.6 on 2025-07-29 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_alter_trainerprofile_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Email Campaign', 'Email Campaign'), ('Cold Call', 'Cold Call'), ('Other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Interested Highly', 'Interested Highly'), ('Register Soon', 'Register Soon'), ('Called Back', 'Called Back'), ('Wrong Enquiry', 'Wrong Enquiry'), ('Not Interested', 'Not Interested'), ('Converted', 'Converted')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('next_follow_up_time', models.TimeField(blank=True, null=True)),
                ('follow_up_status', models.CharField(blank=True, max_length=50)),
                ('interested_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('contact_time', models.TimeField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='invoices.lead')),
            ],
        ),
    ]
