# Generated by Django 5.0.6 on 2025-07-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_alter_lead_follow_up_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_status',
            field=models.CharField(choices=[('New', 'New'), ('Interested Highly', 'Interested Highly'), ('Register Soon', 'Register Soon'), ('Called Back', 'Called Back'), ('Wrong Enquiry', 'Wrong Enquiry'), ('Not Interested', 'Not Interested'), ('Converted', 'Converted')], default='New', max_length=20),
        ),
    ]
