# Generated by Django 5.0.6 on 2025-08-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_alter_lead_follow_up_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='last_contact_date',
            new_name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_follow_up_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_follow_up_time',
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='follow_up_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('Event', 'Event'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Interested Highly', 'Interested Highly'), ('Qualified', 'Qualified'), ('Register Soon', 'Register Soon'), ('Other', 'Other')], default='Interested Highly', max_length=20),
        ),
    ]
