# Generated by Django 5.0.6 on 2025-08-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_rename_last_contact_date_lead_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20, null=True),
        ),
    ]
