# Generated by Django 5.0.6 on 2025-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0041_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +XX-XXXXXXXXX', max_length=20, null=True),
        ),
    ]
