# Generated by Django 5.0.6 on 2026-04-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0044_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicepurchase',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
