# Generated by Django 5.0.6 on 2026-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0046_userprofile_salestarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trn_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TRN Number'),
        ),
    ]
