# Generated by Django 5.0.6 on 2026-06-25 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_coupon_expiry_date_coupon_max_uses_coupon_used_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPortalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('trade_license_number', models.CharField(blank=True, max_length=100)),
                ('trade_license_doc', models.FileField(blank=True, null=True, upload_to='portal/trade_license/')),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('vat_certificate', models.FileField(blank=True, null=True, upload_to='portal/vat/')),
                ('contact_person', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('emirate', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_portal_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPortalAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('emirates_id', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('portal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='invoices.companyportalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('consultant_name_locked', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_form_links', to=settings.AUTH_USER_MODEL)),
                ('pre_selected_courses', models.ManyToManyField(blank=True, to='invoices.course')),
            ],
        ),
    ]
