# Generated by Django 5.0.6 on 2026-07-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0051_fee_reminder_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_override', to='invoices.quotationitem')),
            ],
        ),
    ]
