# Generated by Django 5.0.6 on 2026-07-01 18:37

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0052_add_quotation_item_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='uploaded_certificate',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.khda_cert_upload_path),
        ),
        migrations.AlterField(
            model_name='certificateupload',
            name='certificate_file',
            field=models.FileField(upload_to=invoices.models.student_cert_upload_path),
        ),
        migrations.AlterField(
            model_name='companyportalrequest',
            name='trade_license_doc',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.portal_trade_license_path),
        ),
        migrations.AlterField(
            model_name='companyportalrequest',
            name='vat_certificate',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.portal_vat_cert_path),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_pdf',
            field=models.FileField(upload_to=invoices.models.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='formupload',
            name='form_file',
            field=models.FileField(upload_to=invoices.models.student_form_upload_path),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='profile_pdf',
            field=models.FileField(upload_to=invoices.models.trainer_profile_upload_path),
        ),
    ]
