# Generated by Django 5.0.6 on 2026-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0053_alter_certificate_uploaded_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='oo_advanced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Online/Offline – Advanced'),
        ),
        migrations.AddField(
            model_name='course',
            name='oo_intermediate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Online/Offline – Intermediate'),
        ),
        migrations.AddField(
            model_name='course',
            name='oo_professional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Online/Offline – Professional'),
        ),
        migrations.AddField(
            model_name='course',
            name='priv_advanced',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Private – Advanced'),
        ),
        migrations.AddField(
            model_name='course',
            name='priv_intermediate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Private – Intermediate'),
        ),
        migrations.AddField(
            model_name='course',
            name='priv_professional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Private – Professional'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='level',
            field=models.CharField(blank=True, choices=[('intermediate', 'Intermediate'), ('professional', 'Professional'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='level',
            field=models.CharField(blank=True, choices=[('intermediate', 'Intermediate'), ('professional', 'Professional'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='batch_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='online_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='private_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
