# Generated by Django 5.0.6 on 2026-07-07 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0057_remove_unlisted_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('payment', 'Payment Recorded'), ('status_change', 'Status Changed'), ('export', 'Exported'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Viewed')], max_length=20),
        ),
        migrations.CreateModel(
            name='GatewayPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('tabby', 'Tabby'), ('tamara', 'Tamara')], max_length=10)),
                ('week_start', models.DateField(help_text='Monday of the sales week')),
                ('week_end', models.DateField(help_text='Sunday of the sales week')),
                ('payout_date', models.DateField(help_text='Expected payout day')),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_on_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('short', 'Short Paid')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'gateway'],
                'unique_together': {('gateway', 'week_start')},
            },
        ),
    ]
