# Generated by Django 5.0.6 on 2026-07-08 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0058_gatewaypayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('payment_link', 'Payment Link'), ('tabby', 'Tabby (BNPL)'), ('tamara', 'Tamara (BNPL)'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='CorporateCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('company_location', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('contact_designation', models.CharField(blank=True, max_length=100)),
                ('tax_certificate', models.FileField(blank=True, null=True, upload_to='corporate_docs/tax/')),
                ('trade_license', models.FileField(blank=True, null=True, upload_to='corporate_docs/trade/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_corporate_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Corporate Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateCandidateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corp_company_link', to='invoices.registration')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='invoices.corporatecompany')),
            ],
        ),
    ]
