"""Initial migration

Revision ID: 48345654ea68
Revises: 
Create Date: 2025-08-15 09:00:36.740188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48345654ea68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('class_schedule', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'trainer', ['trainer_id'], ['id'])

    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_schedule', ['class_schedule_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['added_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_interest_id'], ['id'])

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])

    with op.batch_alter_table('lead_quote', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment_provider', ['provider_id'], ['id'])
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'lead', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('monday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('monday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('tuesday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('wednesday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('thursday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('thursday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('friday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('friday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('saturday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('saturday_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sunday_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sunday_end', sa.Time(), nullable=True))

    with op.batch_alter_table('trainer_course', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'trainer', ['trainer_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('can_view_all_leads', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_view_reports', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_courses', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_settings', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('can_manage_settings')
        batch_op.drop_column('can_manage_courses')
        batch_op.drop_column('can_view_reports')
        batch_op.drop_column('can_manage_users')
        batch_op.drop_column('can_view_all_leads')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('active')

    with op.batch_alter_table('trainer_course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('trainer', schema=None) as batch_op:
        batch_op.drop_column('sunday_end')
        batch_op.drop_column('sunday_start')
        batch_op.drop_column('saturday_end')
        batch_op.drop_column('saturday_start')
        batch_op.drop_column('friday_end')
        batch_op.drop_column('friday_start')
        batch_op.drop_column('thursday_end')
        batch_op.drop_column('thursday_start')
        batch_op.drop_column('wednesday_end')
        batch_op.drop_column('wednesday_start')
        batch_op.drop_column('tuesday_end')
        batch_op.drop_column('tuesday_start')
        batch_op.drop_column('monday_end')
        batch_op.drop_column('monday_start')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('bio')
        batch_op.drop_column('hourly_rate')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payment_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead_quote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead_interaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('added_by')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('corporate_training', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('setting')
    # ### end Alembic commands ###
