"""Add followup_time and followup_priority to Lead

Revision ID: e9cd43f660e1
Revises: 
Create Date: 2025-08-12 19:47:02.774175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cd43f660e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('followup_priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('followup_priority')
        batch_op.drop_column('followup_time')

    # ### end Alembic commands ###
