from django.urls import path
from . import views



urlpatterns = [
    path('', views.orbit_dashboard, name='orbit_dashboard'),
    path('manage/users/', views.manage_users, name='manage_users'),
    path('manage/sync-crm/', views.sync_all_crm_users, name='sync_all_crm_users'),
    path('manage/users/<int:user_id>/role/', views.update_user_role, name='update_user_role'),
    path('manage/users/<int:user_id>/edit/', views.edit_user, name='edit_user'),
    path('manage/users/<int:user_id>/delete/', views.delete_user, name='delete_user'),
    path('manage/users/<int:user_id>/change-password/', views.change_user_password, name='change_user_password'),
    path('manage/set-targets/', views.set_targets, name='set_targets'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_invoice/', views.create_invoice, name='create_invoice'),
    path('create_purchase_invoice/', views.create_purchase_invoice, name='create_purchase_invoice'),
    path('add_invoice_items/<int:invoice_id>/', views.add_invoice_items, name='add_invoice_items'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logouts'),
    path('invoice/<int:invoice_id>/edit/', views.edit_invoice, name='edit_invoice'),
    path('invoice/<int:pk>/delete/', views.delete_invoice, name='delete_invoice'),
    path('invoice_purchase/<int:invoice_id>/edit/', views.edit_purchase_invoice, name='edit_purchase_invoice'),
    path('invoice_purchase/<int:pk>/delete/', views.delete_purchase_invoice, name='delete_purchase_invoice'),
    path('quotation/create/', views.create_quotation, name='create_quotation'),
    path('quotation/', views.quotation_dashboard, name='quotation_dashboard'),
    path('quotation_detail/<int:pk>/', views.quotation_detail, name='quotation_detail'),
    path('quotation/<int:pk>/edit/', views.edit_quotation, name='edit_quotation'),
    path('quotation/<int:pk>/delete/', views.delete_quotation, name='delete_quotation'),
    path('register/', views.registration_form, name='registration_form'),
    path('get_course_details/', views.get_course_details, name='get_course_details'),
    path('student-dashboard/', views.student_dashboard, name='student_dashboard'),
    path('edit-registration/<int:pk>/', views.edit_registration, name='edit_registration'),
    path('delete-registration/<int:pk>/', views.delete_registration, name='delete_registration'),
    path('registration/<int:pk>/reassign-consultant/', views.reassign_consultant, name='reassign_consultant'),
    path('print-registration/<int:pk>/', views.print_registration, name='print_registration'),
    path('registration/<int:registration_id>/', views.registration_invoice_detail, name='registration_invoice_detail'),
    path('get_registration_details/', views.get_registration_details, name='get_registration_details'),
    path('get_invoice_details/', views.get_invoice_details, name='get_invoice_details'),
    path('corporate-registration/', views.corporate_registration, name='corporate_registration'),
    path('corporate_dashboard/', views.corporate_dashboard, name='corporate_dashboard'),
    path('corporate-tax-invoice/', views.corporate_tax_invoice_search, name='corporate_tax_invoice_search'),
    path('corporate-tax-invoice/from-pi/<int:pi_id>/', views.create_tax_invoice_from_pi, name='create_tax_invoice_from_pi'),
    path('corporate-invoice-detail/<int:registration_id>/', views.corporate_invoice_detail, name='corporate_invoice_detail'),
    path('corporate-registration/<int:pk>/print/', views.print_corporate_registration, name='print_corporate_registration'),
    path('edit-corporate-registration/<int:pk>/', views.edit_corporate_registration, name='edit_corporate_registration'),
    path('courses/', views.course_list, name='course_list'),
    path('courses/create/', views.course_create, name='course_create'),
    path('courses/<int:course_id>/', views.course_detail, name='course_detail'),
    path('courses/<int:course_id>/update/', views.course_update, name='course_update'),
    path('courses/<int:course_id>/content/create/', views.content_create, name='content_create'),
    path('content/<int:content_id>/delete/', views.content_delete, name='content_delete'),
    path('courses/<int:course_id>/delete/', views.course_delete, name='course_delete'),
    path('certificates/', views.certificate_dashboard, name='certificate_dashboard'),
    path('certificates/create/', views.create_certificate, name='create_certificate'),
    path('certificates/print/<int:pk>/', views.print_certificate, name='print_certificate'),
    path('upload-certificate/<int:registration_id>/', views.upload_certificate, name='upload_certificate'),
    path('certificates/khda-form/', views.khda_certificate_form, name='khda_certificate_form'),
    path('certificates/create-khda/', views.create_khda_certificate, name='create_khda_certificate'),
    path('certificates/<int:pk>/delete/', views.delete_certificate, name='delete_certificate'),
    path('upload-form/<int:registration_id>/', views.upload_form, name='upload_form'),
    path('proposals/', views.proposal_dashboard, name='proposal_dashboard'),
    path('proposals/create/', views.create_proposal, name='create_proposal'),
    path('proposals/<int:pk>/edit/', views.edit_proposal, name='edit_proposal'),
    path('proposals/<int:pk>/delete/', views.delete_proposal, name='delete_proposal'),
    path('proposals/<int:pk>/print/', views.print_proposal, name='print_proposal'),
    path('trainer-profile/create/', views.create_trainer_profile, name='create_trainer_profile'),
    path('trainer-profile/<int:pk>/edit/', views.edit_trainer_profile, name='edit_trainer_profile'),
    path('trainer-profile/list/', views.trainer_profile_list, name='trainer_profile_list'),
    path('trainer-profile/<int:pk>/delete/', views.delete_trainer_profile, name='delete_trainer_profile'),
    path('subscription/', views.subscription, name='subscription'),
    path('company-profile/create/', views.create_company_profile, name='create_company_profile'),
    path('company-profile/<int:pk>/edit/', views.edit_company_profile, name='edit_company_profile'),
    path('company-profile/list/', views.company_profile_list, name='company_profile_list'),
    path('company-profile/<int:pk>/delete/', views.delete_company_profile, name='delete_company_profile'),
    path('remove_logo/<int:proposal_id>/', views.remove_logo, name='remove_logo'),
    path('payment-link/', views.payment_link, name='payment_link'),
    # Coupon URLs
    path('coupons/', views.coupon_list, name='coupon_list'),
    path('coupons/create/', views.create_coupon, name='create_coupon'),
    path('coupons/<int:pk>/edit/', views.edit_coupon, name='edit_coupon'),
    path('coupons/<int:pk>/delete/', views.delete_coupon, name='delete_coupon'),
    path('validate-coupon/', views.validate_coupon, name='validate_coupon'),
    # Reports
    path('reports/revenue/', views.revenue_report, name='revenue_report'),
    path('reports/revenue/export/', views.export_revenue_csv, name='export_revenue_csv'),
    # New Reports
    path('reports/aging/', views.receivables_aging, name='receivables_aging'),
    path('reports/vat/', views.vat_report, name='vat_report'),
    path('reports/enrollment/', views.enrollment_report, name='enrollment_report'),
    path('reports/certificates/', views.certificate_report, name='certificate_report'),
    # Search & Notifications
    path('search/', views.global_search, name='global_search'),
    path('notifications/', views.get_notifications, name='get_notifications'),
    path('notifications/<int:notif_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('invoice/<int:pk>/mark-paid/', views.mark_invoice_paid, name='mark_invoice_paid'),
    # Smart registration search (autocomplete)
    path('api/search-registrations/', views.search_registrations, name='search_registrations'),
    # Company Portal (public)
    path('portal/company/<str:token>/', views.company_portal, name='company_portal'),
    path('portal/company/<str:token>/success/', views.company_portal_success, name='company_portal_success'),
    path('portal/company/<str:token>/attendees/', views.company_portal_add_attendees, name='company_portal_add_attendees'),
    # Company Portal (admin)
    path('admin-portal/', views.admin_company_portal, name='admin_company_portal'),
    path('admin-portal/generate/', views.generate_company_portal_link, name='generate_company_portal_link'),
    path('admin-portal/<int:pk>/approve/', views.approve_company_portal, name='approve_company_portal'),
    # Student Form Links
    path('portal/student-links/', views.student_form_links, name='student_form_links'),
    path('portal/student-links/generate/', views.generate_student_form_link, name='generate_student_form_link'),
    path('portal/student/<str:token>/', views.student_self_register, name='student_self_register'),
    path('portal/welcome-letter/<int:pk>/', views.welcome_letter_printable, name='welcome_letter_printable'),
    path('portal/enrollment-letter/<str:token>/', views.enrollment_letter_printable, name='enrollment_letter_printable'),
    # Student status update
    path('student/<int:pk>/status/', views.update_student_status, name='update_student_status'),
    # Bulk invoice actions
    path('invoices/bulk-action/', views.bulk_invoice_action, name='bulk_invoice_action'),
    # Invoice payments
    path('invoice/<int:pk>/payments/', views.invoice_payments, name='invoice_payments'),
    path('invoice/<int:pk>/payments/add/', views.add_invoice_payment, name='add_invoice_payment'),
    # Training schedule
    path('schedule/', views.training_schedule_list, name='training_schedule_list'),
    path('schedule/create/', views.training_schedule_create, name='training_schedule_create'),
    path('schedule/<int:pk>/edit/', views.training_schedule_edit, name='training_schedule_edit'),
    path('schedule/<int:pk>/delete/', views.training_schedule_delete, name='training_schedule_delete'),
    # Expenses
    path('expenses/', views.expense_list, name='expense_list'),
    path('expenses/create/', views.expense_create, name='expense_create'),
    path('expenses/<int:pk>/edit/', views.expense_edit, name='expense_edit'),
    path('expenses/<int:pk>/delete/', views.expense_delete, name='expense_delete'),
    path('expenses/report/', views.expense_report, name='expense_report'),
    # Audit log
    path('audit/', views.audit_log_view, name='audit_log'),
    # Fee Reminder
    path('fee-reminders/', views.fee_reminder_dashboard, name='fee_reminder_dashboard'),
    # CRM SSO Bridge
    path('crm-jump/', views.crm_jump, name='crm_jump'),
    path('crm-auth/', views.crm_auth, name='crm_auth'),
    # CRM Lead lookup (used by registration form live search)
    path('api/crm-lead/<int:lead_id>/', views.api_crm_lead_lookup, name='api_crm_lead_lookup'),
    # Gateway Payouts (Tabby / Tamara)
    path('finance/gateway-payouts/', views.gateway_payout_list, name='gateway_payout_list'),
    # Student emails
    path('registration/<int:pk>/send-enrollment-letter/', views.send_enrollment_letter, name='send_enrollment_letter'),
    # Corporate Company PI data APIs
    path('api/search-corporate-companies/', views.api_search_corporate_companies, name='api_search_corporate_companies'),
    path('api/corporate-pi-data/', views.api_corporate_pi_data, name='api_corporate_pi_data'),
    # Corporate Company (company-first flow)
    path('corporate-companies/', views.corporate_company_list, name='corporate_company_list'),
    path('corporate-companies/create/', views.corporate_company_create, name='corporate_company_create'),
    path('corporate-companies/<int:pk>/', views.corporate_company_detail, name='corporate_company_detail'),
    path('corporate-companies/<int:pk>/edit/', views.corporate_company_edit, name='corporate_company_edit'),
    path('corporate-companies/<int:pk>/delete/', views.corporate_company_delete, name='corporate_company_delete'),
    path('corporate-companies/<int:pk>/add-candidate/', views.corporate_add_candidate, name='corporate_add_candidate'),
    path('corporate-companies/<int:pk>/generate-portal/', views.corporate_company_generate_portal, name='corporate_company_generate_portal'),
    path('corporate-companies/<int:pk>/dashboard-url/', views.corporate_company_get_dashboard_url, name='corporate_company_get_dashboard_url'),
    path('company-dashboard/<str:token>/', views.company_dashboard_portal, name='company_dashboard_portal'),
    path('corporate-companies/legacy/', views.corporate_legacy_registrations, name='corporate_legacy_registrations'),
]